[package]
name = "rgss-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "RPG Maker 游戏根检测：2000 / 2003 / XP / VX / VX Ace"
keywords = ["rgss", "rpg-maker"]
categories = ["game-development"]
publish = false

[dependencies]
encoding_rs = { workspace = true }
